#!/bin/bash
source ../config

export USER="$CERT_DIR/test0.cert.pem"
export USER1="$CERT_DIR/test1.cert.pem"
export USER2="$CERT_DIR/test2.cert.pem"
export USER3="$CERT_DIR/test3.cert.pem"
export USER4="$CERT_DIR/test4.cert.pem"

# needed by some new ACL tests
#export PWS="$SAME_SENSOR_HOME/tests/pws"
export USER_KEY="$CERT_DIR/test0.key.pem"
export USER1_KEY="$CERT_DIR/test1.key.pem"
export USER2_KEY="$CERT_DIR/test2.key.pem"
export USER3_KEY="$CERT_DIR/test3.key.pem"
export USER4_KEY="$CERT_DIR/test4.key.pem"

export CA="/C=IT/O=IGI/CN=Test CA"
export CA_CERN="/C=CH/O=CERN/OU=GRID/CN=CERN CA"
#export GRIDMAP="$SAME_SENSOR_HOME/tests/gridmap-test-1928" # gridmap config for "test" & "lxb1928"
#export ACCOUNT=".$vo_name"    # Mapped user account for grid_mapfile
export ROLE="test_role"      # Greate/delete Role
export GROUP="test_group"      # Create/delete Group
export OP="list"              # Operation value (list, all, add,... ) for test ACL management
export ALLOW="allow"          # Value  (allow or deny) for test ACL management

#---------- Values for attributes in voms-admin commands
export ATTRIBUTE="TEST_ATTRIBUTE"
export ATTVALUE="TEST Attribute value"
export ATTDESC="Test Attribute description"

#--------- temporary files ------------------------------------
export voms_tmp=$HOME/voms_test_tmp
export voms_stderr=$HOME/voms_test_stderr
export tempo=$HOME/voms_tempo
export cert_dir=$HOME/voms_certdir
